### ISSUE TITLE
dreadful -34018 error

### ISSUE THREAD

**Issue by armandzwan** [reidmain/FDKeychain#10]
I'm running into the dreadful -34018 error. Do you have any more tips beside:
http://stackoverflow.com/questions/29740952/osstatus-error-code-34018

**Comment by reidmain** [comment]
Unfortunately no @armandzwan. The only information I have is the same information that is linked in that StackOverflow post https://forums.developer.apple.com/message/9225#9225

At this point it seems that we are at Apple's mercy.

**Comment by waqqas-abdulkareem** [comment]
Just want to mention that enabling the 'Keychain sharing' capability resolved this issue for me.
