### ISSUE TITLE
Keychain error -34018

### ISSUE THREAD

**Issue by omarojo** [reidmain/FDKeychain#7]
Getting this error, constantly while saving or reading. 
I found this thread in apple forums, but what can we do ? 
https://forums.developer.apple.com/thread/4743

**Comment by reidmain** [comment]
I've heard other reports of this but there is nothing that FDKeychain can do as far as I am aware. It appears to be a race condition inside iOS that Apple has identified and will most likely fix in iOS 10 if they don't fix it in a minor release of iOS 9.
