### ISSUE TITLE
Making the last pod work on watch 2 requires moving the version tag

### ISSUE THREAD

**Issue by seviu** [reidmain/FDKeychain#9]
Hi,

Thanks for merging my change on the pod.

However there is one last thing that needs to be done so that an app wit ha watchos 2 target can work with it, which is to move the version tag 1.2.2 to the latest commit.

Thanks a lot!

Sebastian

**Comment by reidmain** [comment]
Hi @seviu. Sorry for taking so long to respond to this. I really have no excuse other than laziness and just not paying attention to my public GitHub account.

I merged in your [pull request](https://github.com/reidmain/FDKeychain/pull/8) and I will update to CocoaPods 1.0 this weekend and then update v1.2.2 of this pod to point to the latest (or maybe I'll just end up publishing v1.2.3).

**Comment by reidmain** [comment]
v1.3.0 of FDKeychain has been published to CocoaPods and it contains support for both watchOS and tvOS.
